### ISSUE TITLE
Cannot find executables

### ISSUE THREAD

**Issue by hcguo** [ThundeRatz/ros_yolo2#8]
I have successfully built from source folder. However, I didn't find executables. I sourced /devel/setup.bash then use rosrun but no executable shows. Any hint? Thanks a lot.

**Comment by tiagoshibata** [comment]
The library is using nodelets, a ROS feature to put multiple "nodes" in the same process and support zero-copy message transfers. The build generates shared libraries to be loaded in the same process instead of individual executables.

Instructions to run the library are available in the [darknet mailing list](https://groups.google.com/forum/#!topic/darknet/CQLpLwZT4TE). You can look there and in the [official nodelet docs](http://wiki.ros.org/nodelet) and [tutorials](http://wiki.ros.org/nodelet/Tutorials) for help.

I'm willing add more instructions and examples of launchfiles to ros_yolo2, since many people have never used nodelets before and get lost after the build. However, I always forget to write them :) . If you feel like contributing, you can create a pull request adding more instructions to the README.md file, based on the instructions I provided on the mailing list. Else I'll probably write the docs sometime in the forthcoming weeks.

Please reply back with your results and let me know if you have further problems!

**Comment by hcguo** [comment]
Hi Tiago,
Thank you for the hint. It's helpful and I found the launch file you replied in mailing list. I run it on TX1 with GPU and got ~8 FPS on detection. Since I saw in mailing list that TK1 could reach 10 FPS, I am trying to figure out what happens on my TX1. I am running with ROS kinetic and video stream is from ZED camera wrapper. I'll update if have any progress.

**Comment by tiagoshibata** [comment]
The TK1 reaches about 8.72 FPS for me. Compiling with optimizations (`catkin_make -DCMAKE_BUILD_TYPE=Release`) should help (not sure if you enabled them already).
